-- Database schema for receipts bot
-- This file is executed on bot startup if tables don't exist

CREATE SCHEMA app_receipts_bot;

SET search_path TO 'app_receipts_bot';

CREATE TABLE version(version text primary key);

INSERT INTO version VALUES ('0.1');

-- User table
CREATE TABLE "user" (
    user_id BIGINT PRIMARY KEY,
    username TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Category table for item classification
CREATE TABLE category (
    category_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name text NOT NULL UNIQUE,
    description TEXT,
    ai_notes TEXT,  -- Additional instructions for Claude AI about category assignment
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Merchant table
CREATE TABLE merchant (
    merchant_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    city TEXT,
    country TEXT,
    address TEXT,
    logo_description TEXT,
    ai_notes TEXT,  -- Additional instructions for Claude AI about merchant recognition
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Image table
CREATE TABLE image (
    image_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT REFERENCES "user"(user_id) ON DELETE CASCADE,
    file_id TEXT NOT NULL,  -- Telegram file_id for re-downloading
    orig_file_path TEXT,  -- Local filesystem path
    orig_file_size INTEGER,
    processed_file_path TEXT,
    processed_file_size INTEGER,
    mime_type TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Transaction table
CREATE TABLE transaction (
    transaction_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE,
    time TIME,
    currency TEXT DEFAULT 'EUR',
    net_amount NUMERIC,
    vat_amount NUMERIC,
    brutto_amount NUMERIC,
    payment_method TEXT,  -- card, cash, paypal, etc.
    card_number TEXT,  -- last 4 digits
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- AI Analysis table - tracks Claude AI processing results
CREATE TABLE ai_analysis (
    analysis_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_name TEXT NOT NULL,  -- e.g., claude-sonnet-4-5-20250929
    extraction_status TEXT,  -- complete, partial, needs_review, failed, refused
    input_tokens INTEGER,
    output_tokens INTEGER,
    raw_data JSONB,  -- Full Claude AI response for debugging/reprocessing
    error_message TEXT,  -- Error message if analysis failed
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Receipt table
CREATE TABLE receipt (
    receipt_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_id INTEGER REFERENCES image(image_id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES "user"(user_id) ON DELETE CASCADE,
    merchant_id INTEGER REFERENCES merchant(merchant_id) ON DELETE SET NULL,
    transaction_id INTEGER REFERENCES transaction(transaction_id) ON DELETE SET NULL,
    ai_analysis_id INTEGER REFERENCES ai_analysis(analysis_id) ON DELETE SET NULL,
    processing_status TEXT DEFAULT 'pending',  -- created, pre-processed, analyzing, completed, failed
    user_notes TEXT,  -- Optional user-provided notes to help Claude AI (from caption)
    is_deleted BOOLEAN DEFAULT FALSE,  -- soft delete flag
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Receipt item table
CREATE TABLE receipt_item (
    item_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_id INTEGER REFERENCES receipt(receipt_id) ON DELETE CASCADE,
    category_id INTEGER REFERENCES category(category_id) ON DELETE SET NULL,
    item_name TEXT NOT NULL,
    article_number TEXT,
    quantity NUMERIC,
    unit_price NUMERIC,
    total_price NUMERIC,
    is_deleted BOOLEAN DEFAULT FALSE,  -- soft delete flag for user edits
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for performance
CREATE INDEX idx_receipt_user_id ON receipt(user_id);
CREATE INDEX idx_receipt_merchant_id ON receipt(merchant_id);
CREATE INDEX idx_receipt_transaction_id ON receipt(transaction_id);
CREATE INDEX idx_receipt_ai_analysis_id ON receipt(ai_analysis_id);
CREATE INDEX idx_receipt_status ON receipt(processing_status);
CREATE INDEX idx_transaction_date ON transaction(date);
CREATE INDEX idx_ai_analysis_model ON ai_analysis(model_name);
CREATE INDEX idx_ai_analysis_status ON ai_analysis(extraction_status);
CREATE INDEX idx_receipt_item_receipt_id ON receipt_item(receipt_id);
CREATE INDEX idx_receipt_item_category_id ON receipt_item(category_id);
CREATE INDEX idx_image_user_id ON image(user_id);

--------

CREATE VIEW v_receipt_summary AS
SELECT
    r.receipt_id,
    t.date AS transaction_date,
    r.merchant_id,
    m.name AS merchant_name,
    m.city AS merchant_city,
    t.brutto_amount,
    COUNT(ri.item_id) AS item_count,
    SUM(ri.total_price) AS total_items_price,
    r.transaction_id,
    r.processing_status,
    SUM(ri.total_price) - t.brutto_amount AS price_difference
FROM
    receipt r
LEFT JOIN
    merchant m ON r.merchant_id = m.merchant_id
LEFT JOIN
    transaction t ON r.transaction_id = t.transaction_id
LEFT JOIN
    receipt_item ri ON r.receipt_id = ri.receipt_id
WHERE
    r.is_deleted = FALSE AND ri.is_deleted = FALSE
GROUP BY
    r.receipt_id, m.name, m.city, t.date, t.brutto_amount;