-- Database schema for receipts bot
-- This file is executed on bot startup if tables don't exist

CREATE SCHEMA app_receipts_bot;

SET search_path TO 'app_receipts_bot';

CREATE TABLE version(version text primary key);

INSERT INTO version VALUES ('0.1');

-- User table
CREATE TABLE "user" (
    user_id BIGINT PRIMARY KEY,
    username TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Category table for item classification
CREATE TABLE category (
    category_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name TEXT NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Image table
CREATE TABLE image (
    image_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT REFERENCES "user"(user_id) ON DELETE CASCADE,
    file_id TEXT NOT NULL,  -- Telegram file_id for re-downloading
    orig_file_path TEXT,  -- Local filesystem path
    orig_file_size INTEGER,
    processed_file_path TEXT,
    processed_file_size INTEGER,
    mime_type TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Receipt table
CREATE TABLE receipt (
    receipt_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_id INTEGER REFERENCES image(image_id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES "user"(user_id) ON DELETE CASCADE,
    merchant TEXT,
    receipt_date DATE,
    receipt_time TIME,
    total_amount NUMERIC,
    currency TEXT DEFAULT 'EUR',
    processing_status TEXT DEFAULT 'pending',  -- pending, processing, completed, failed
    raw_data JSONB,  -- Full Claude AI response for debugging/reprocessing
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Receipt item table
CREATE TABLE receipt_item (
    item_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_id INTEGER REFERENCES receipt(receipt_id) ON DELETE CASCADE,
    category_id INTEGER REFERENCES category(category_id) ON DELETE SET NULL,
    item_name TEXT NOT NULL,
    quantity NUMERIC,
    unit_price NUMERIC,
    total_price NUMERIC,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for performance
CREATE INDEX idx_receipt_user_id ON receipt(user_id);
CREATE INDEX idx_receipt_date ON receipt(receipt_date);
CREATE INDEX idx_receipt_status ON receipt(processing_status);
CREATE INDEX idx_receipt_item_receipt_id ON receipt_item(receipt_id);
CREATE INDEX idx_receipt_item_category_id ON receipt_item(category_id);
CREATE INDEX idx_image_user_id ON image(user_id);

--------
